import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/main.module.css'


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>LIFF-TEX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainStyle}>
        <div>test</div>
        <input type="text" className={styles.inputStyle}/>
      </main>
    </>
  )
}

export default Home
