import type { NextPage } from 'next'
import Head from 'next/head'
import Script from 'next/script'
import { ChangeEvent, useRef } from 'react'
import { useState } from 'react'

import styles from '../styles/main.module.css'
import katex from 'katex'
import renderMathInElement from 'katex/dist/contrib/auto-render'

const Home: NextPage = () => {
  const [inputEl, setInputEl] = useState("")

  const handleChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
    const currentText = e.target.value
    setInputEl(currentText)
    
    const katexArea = document.getElementById("katex-area")
    if (!katexArea) {
      console.log("There is no such a HTMLElement.")
    }
    
    katex.render(String.raw`${currentText}`, katexArea!, {
      throwOnError: false,
      displayMode: true
    })
  }


  return (
    <>
      <Head>
        <title>LIFF-TEX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css" integrity="sha384-KiWOvVjnN8qwAZbuQyWDIbfCLFhLXNETzBQjA/92pIowpC0d2O3nppDGQVgwd2nB" crossOrigin="anonymous"></link>
      </Head>

      <main className={styles.mainStyle}>
        <div className={styles.previewStyle} id="katex-area">
          
        </div>
        <textarea
          value={inputEl}
          className={styles.inputStyle}
          onChange={(e) => handleChange(e)}
        />
      </main>
    </>
  )
}

export default Home
